### ISSUE TITLE
Purpose of this module?

### ISSUE THREAD

**Issue by adamski** [izzyreal/juce-raw-keyboard-input-module#1]
I came across this module from https://github.com/Normalised/AudioProgrammerCPM_Recipes

I'm curious what the purpose and use-case is for the module?

**Comment by izzyreal** [comment]
Hi, this module is for handling raw untransformed keyboard input within a JUCE project. JUCE's default keyboard handling includes quite a few transformations on and exclusions of keycodes. Additionally JUCE does not provide a unified interface for key down and key up events. For my project, VMPC2000XL, an emulator of the Akai MPC2000XL, I need game-engine style keyboard handling. So if you need something similar and want to get beyond any of the mentioned limitations in JUCE, you can use this module.
